steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/icfpcontest2020/dockerfiles']
- name: 'python'
  args: ['python', 'cloud_build_check.py']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/client:$SHORT_SHA', '.']
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['run', "--network=cloudbuild",'--entrypoint=./strict_run.sh', '-t', 'client:$SHORT_SHA', 'https://dummy-server-prtffs3u5a-uc.a.run.app/', 'test_key']
images: ['gcr.io/$PROJECT_ID/client:$SHORT_SHA']
