steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './portal/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/portal:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/portal:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'portal'
  - '--image'
  - 'gcr.io/$PROJECT_ID/portal:$SHORT_SHA'
  - '--region'
  - 'us-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'