steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/icfpcontest2020/dockerfiles']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './dockerfiles/dockerfiles/python/Dockerfile', '-t', 'client:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './Dockerfile.server', '-t', 'judge-dummy:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-itd', 'judge-dummy:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'client:$SHORT_SHA', './run.sh', 'https://dummy-server-prtffs3u5a-uc.a.run.app', 'test_key']
